describe('template spec', () => {
  it('Login with valid credential', () => {
    cy.visit('https://the-internet.herokuapp.com/login')
    cy.wait(1)
    cy.get('#username').type("tomsmith").should("be.visible")
    cy.wait(1)
    cy.get('#password').type("SuperSecretPassword!")
    cy.get('.fa').click()
    cy.wait(1)
    cy.get('.subheader')
      .should('have.text', 'Welcome to the Secure Area. When you are done click logout below.')
  })
  it('Login valid credential with ignore lettercase', () => {
    cy.visit('https://the-internet.herokuapp.com/login')
    cy.wait(1)
    cy.get('#username').type("tomsmITh").should("be.visible")
    cy.wait(1)
    cy.get('#password').type("SuperSecretPassword!")
    cy.get('.fa').click()
    cy.wait(2)
    cy.get('#flash')
      .should('contain', 'Your username is invalid!')
  })
  it('Login invalid username', () => {
    cy.visit('https://the-internet.herokuapp.com/login')
    cy.wait(1)
    cy.get('#username').type("hikmah").should("be.visible")
    cy.wait(1)
    cy.get('#password').type("SuperSecretPassword!")
    cy.get('.fa').click()
    cy.wait(2)
    cy.get('#flash')
      .should('contain', 'Your username is invalid!')
  })
  it('Login invalid password', () => {
    cy.visit('https://the-internet.herokuapp.com/login')
    cy.wait(1)
    cy.get('#username').type("tomsmith").should("be.visible")
    cy.wait(1)
    cy.get('#password').type("hikmah")
    cy.get('.fa').click()
    cy.wait(2)
    cy.get('#flash')
      .should('contain', 'Your password is invalid!')
  })
  it('Login null username', () => {
    cy.visit('https://the-internet.herokuapp.com/login')
    cy.wait(1)
    cy.get('#username')
    cy.wait(1)
    cy.get('#password').type("SuperSecretPassword!")
    cy.get('.fa').click()
    cy.wait(1)
    cy.get('#flash')
      .should('contain', 'Your username is invalid!')
  })
  it('Login null password', () => {
    cy.visit('https://the-internet.herokuapp.com/login')
    cy.wait(1)
    cy.get('#username').type("tomsmith").should("be.visible")
    cy.wait(1)
    cy.get('#password')
    cy.get('.fa').click()
    cy.wait(1)
    cy.get('#flash')
      .should('contain', 'Your password is invalid!')
  })

})